deploy-pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -a dists pool index.html public/
  artifacts:
    paths:
      - public
  pages: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "gh-pages"'
