name: Mirror gh-pages to GitLab

on:
  push:
    branches:
      - gh-pages

jobs:
  mirror-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push gh-pages to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/lay2dev/botdrop-packages.git
          git push gitlab HEAD:gh-pages --force
